'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { createBrowserClient } from '@/lib/supabase/client'

export default function AcceptTermsForm() {
  const router = useRouter()
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  async function handleAcceptTerms() {
    setLoading(true)
    setError(null)

    try {
      const supabase = createBrowserClient()
      const { data: { user } } = await supabase.auth.getUser()

      if (!user) {
        router.push('/auth/login')
        return
      }

      const { error: updateError } = await supabase
        .from('user_credits')
        .update({ terms_accepted: true })
        .eq('user_id', user.id)

      if (updateError) {
        setError('Failed to accept terms. Please try again.')
        return
      }

      // Check onboarding status
      const { data: userCredits } = await supabase
        .from('user_credits')
        .select('onboarding_complete')
        .eq('user_id', user.id)
        .single()

      if (!userCredits?.onboarding_complete) {
        router.push('/onboarding')
      } else {
        router.push('/portfolio')
      }

      router.refresh()
    } catch {
      setError('An unexpected error occurred. Please try again.')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="flex min-h-screen items-center justify-center px-4" style={{ backgroundColor: 'var(--bg-base)' }}>
      <div className="w-full max-w-lg">
        <h1 className="mb-2 text-2xl font-semibold" style={{ color: 'var(--text-primary)' }}>
          Terms of Service
        </h1>
        <p className="mb-6 text-sm" style={{ color: 'var(--text-secondary)' }}>
          Please review and accept our terms before continuing.
        </p>

        {/* Terms content */}
        <div
          className="mb-6 max-h-80 overflow-y-auto rounded-lg p-5 text-sm leading-relaxed"
          style={{
            backgroundColor: 'var(--bg-surface)',
            border: '1px solid var(--border-subtle)',
            color: 'var(--text-secondary)',
          }}
        >
          <h2 className="mb-3 text-base font-semibold" style={{ color: 'var(--text-primary)' }}>
            1. Acceptance of Terms
          </h2>
          <p className="mb-4">
            By accessing or using Crypto Analytix, you agree to be bound by these Terms of Service.
            If you do not agree, do not use the platform.
          </p>

          <h2 className="mb-3 text-base font-semibold" style={{ color: 'var(--text-primary)' }}>
            2. Not Financial Advice
          </h2>
          <p className="mb-4">
            Crypto Analytix provides analysis, education, and market intelligence for informational
            purposes only. Nothing on this platform constitutes financial advice, investment advice,
            trading advice, or any other sort of advice. You should not treat any of the content as
            such. You are solely responsible for your own investment decisions.
          </p>

          <h2 className="mb-3 text-base font-semibold" style={{ color: 'var(--text-primary)' }}>
            3. Risk Disclosure
          </h2>
          <p className="mb-4">
            Cryptocurrency trading involves substantial risk of loss and is not suitable for every
            investor. The valuation of cryptocurrencies may fluctuate, and as a result, you may lose
            more than your original investment. Past performance is not indicative of future results.
          </p>

          <h2 className="mb-3 text-base font-semibold" style={{ color: 'var(--text-primary)' }}>
            4. Account Security
          </h2>
          <p className="mb-4">
            You are responsible for maintaining the confidentiality of your account credentials.
            Exchange connections are read-only by default. Crypto Analytix never stores your
            exchange API keys directly — all exchange authentication is handled securely through
            our partner SnapTrade.
          </p>

          <h2 className="mb-3 text-base font-semibold" style={{ color: 'var(--text-primary)' }}>
            5. Privacy
          </h2>
          <p className="mb-4">
            Your portfolio data, trading history, and Pelican AI conversations are private and
            encrypted. We do not sell your data. Portfolio data is never revealed in community
            contexts.
          </p>

          <h2 className="mb-3 text-base font-semibold" style={{ color: 'var(--text-primary)' }}>
            6. Pelican AI
          </h2>
          <p>
            Pelican AI provides contextual analysis based on your portfolio and market data.
            Pelican responses are generated by AI and should be verified independently. Pelican
            is not a licensed financial advisor.
          </p>
        </div>

        {error && (
          <p className="mb-4 text-sm" style={{ color: 'var(--data-negative)' }}>
            {error}
          </p>
        )}

        <button
          onClick={handleAcceptTerms}
          disabled={loading}
          className="btn btn-primary w-full justify-center py-3 text-base"
        >
          {loading ? 'Accepting...' : 'I Accept the Terms of Service'}
        </button>

        <p className="mt-4 text-center text-xs" style={{ color: 'var(--text-muted)' }}>
          By accepting, you acknowledge you have read and understood these terms.
        </p>
      </div>
    </div>
  )
}
